version: 0.2

env:
  variables:
    JOB_NAMES: "<job01>"
    BUCKET_NAME: "<s3://glue-code-dev>"
    REGION_NAME: "ap-south-1"

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install awscli
  build:
    commands:
      - export COMMIT_ID=$(aws codecommit get-commit --repository-name git@github.com:atulk29/glue_job.git --commit-id $(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -d':' -f2) | jq -r '.commitId')
      - |
        for JOB_NAME in $JOB_NAMES; do
          DIFF=$(aws glue get-job --job-name $JOB_NAME --query 'job.ScriptLocation' | cut -d'/' -f4- | xargs -I {} aws s3 cp {} s3://$BUCKET_NAME/glue-job-script --quiet --region $REGION_NAME --sse AES256 && aws s3api head-object --bucket $BUCKET_NAME --key glue-job-script --if-modified-since "$(aws codecommit get-commit --repository-name $REPO_NAME --commit-id $COMMIT_ID | jq -r '.commit.committer.date' | date -u +"%a, %d %b %Y %T GMT")" || echo "No changes in the Glue job script."
          if [[ -n "$DIFF" ]]; then
            aws s3 cp <path-to-new-script> s3://$BUCKET_NAME/glue-job-script --region $REGION_NAME --sse AES256
            aws glue update-job --job-name $JOB_NAME --job-update "{\"JobCommand\":{\"ScriptLocation\":\"s3://$BUCKET_NAME/glue-job-script\"}}" --region $REGION_NAME
          fi
        done

