version: 0.2

env:
  variables:
    JOB_NAMES: "<job01.py>"
    BUCKET_NAME: "<s3://glue-code-dev>"
    REGION: "<ap-south-1>"

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install awscli
  build:
    commands:
      - export COMMIT_ID=$(aws codecommit get-commit --repository-name <repository-name> --commit-id $(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -d':' -f2) | jq -r '.commitId')
      - |
        for JOB_NAME in $JOB_NAMES; do
          DIFF=$(aws glue get-job --job-name $JOB_NAME | jq -r '.job.ScriptLocation' | cut -d'/' -f7- | xargs aws s3 cp - s3://$BUCKET_NAME/glue-job-script --quiet --region $REGION --sse AES256 && aws s3api head-object --bucket $BUCKET_NAME --key glue-job-script --if-modified-since "$(aws codecommit get-commit --repository-name <repository-name> --commit-id $COMMIT_ID | jq -r '.commit.committer.date' | date -u +"%a, %d %b %Y %T GMT")" || echo "No changes in the Glue job script.")
          if [[ -n "$DIFF" ]]; then aws s3 cp <path-to-new-script> s3://$BUCKET_NAME/glue-job-script --region $REGION --sse AES256 && aws glue update-job --job-name $JOB_NAME --job-update "{\"JobCommand\":{\"ScriptLocation\":\"s3://$BUCKET_NAME/glue-job-script\"}}" --region $REGION; fi
        done
