version: 0.2

env:
  variables:
    S3_BUCKET_NAME: "s3://glue-code-dev"
    CODECOMMIT_REPO_NAME: "your-repo"
    GLUE_JOB_NAMES: "job1"

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - apt-get update && apt-get install -y python3-pip
      - pip3 install awscli

  build:
    commands:
      - aws s3 cp s3://${S3_BUCKET_NAME}/job01.py .
      - aws codepipeline get-pipeline-state --name your-pipeline > pipeline_state.json
      - LATEST_COMMIT=$(jq -r '.stageStates[0].actionStates[0].latestExecution.externalExecutionId' pipeline_state.json)
      - LATEST_FILE=$(aws codecommit get-file --repository-name ${CODECOMMIT_REPO_NAME} --file-path your-code.py --commit-id $LATEST_COMMIT --query 'fileContent' --output text)
      - echo "$LATEST_FILE" > latest-code.py
      - for JOB_NAME in $(echo ${GLUE_JOB_NAMES} | tr ',' ' ')
        do
          aws glue get-job --job-name $JOB_NAME > job_state.json
          CURRENT_HASH=$(jq -r '.job.Command.ScriptLocation' job_state.json | cut -d'#' -f2)
          LATEST_HASH=$(md5sum latest-code.py | cut -d' ' -f1)
          if [ "$CURRENT_HASH" != "$LATEST_HASH" ]
          then
            aws glue update-job --job-name $JOB_NAME --job-args '{"--arg1":"value1", "--arg2":"value2"}'
            aws s3 cp latest-code.py s3://${S3_BUCKET_NAME}/
          fi
        done
